{"name": "Неуспешный вход с неверным логином", "status": "passed", "description": "Проверка ошибки при входе с неверным логином", "steps": [{"name": "Авторизация пользователя: POST /api/auth/login", "status": "passed", "parameters": [{"name": "email", "value": "'wrongemail@example.com!'"}, {"name": "password", "value": "'}z|8_>A''"}], "start": 1719860648494, "stop": 1719860648898}], "parameters": [{"name": "email", "value": "'wrongemail@example.com!'"}], "start": 1719860648494, "stop": 1719860648899, "uuid": "6d6e882f-fa0d-4acb-955c-3fa380663920", "historyId": "90601fe0556272828218917c2c0f1571", "testCaseId": "5703d25b8427c62e538b4fb3b4a16fd3", "fullName": "tests.test_user.TestLoginUser#test_login_bad_login_failure", "labels": [{"name": "feature", "value": "Вход пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "NB-4179"}, {"name": "thread", "value": "11668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}